### PR TITLE
Implement cacheStorage using IndexedDB

### PR DESCRIPTION
**Pull request by nikrolls**
IndexedDB has no storage limit so doesn't need splitting, and should be much more performant.

TODO before this is merged: calculating storage size.

### CODE REVIEW

**Comment by gorhill** [comment]
Be aware that there is a bad side effect for using IndexedDB, as reported on ABP's issue tracker: <https://issues.adblockplus.org/ticket/4570>.

**Comment by nikrolls** [comment]
Yeah, it's not ideal. It's going to be a decision between performance and stability (not great with string-splitting) and the potential for user settings to be accidentally lost (not great for user experience). Microsoft have some perf tooling they use so I'll ask for their help in comparing the two methods.

On a positive note, this will only be temporary. I've been told that the 1MB limit is a purely technical limitation rather than an arbitrary decision, and it will become unlimited in an update coming soon (I would assume RS2 / Creators Update, but it's not in Insider builds yet so I can't be certain). So a stop-gap solution may be ok until then, as long as the added cost of smartly migrating the data is worth it.

**Comment by gorhill** [comment]
Would a mixed solution work?

Say all settings use `browser.storage.local`, while all cached/compiled assets use IndexedDB. Even without the current Edge issue, this would probably be a good idea to make a distinction between user settings and transient data which can be erased with no consequences other than having to reload/recompile such data. Unless a user has a **huge** amount of custom filters (very unlikely), all user settings should typically fit within the MS limit.

**Comment by nikrolls** [comment]
That's actually a really good idea! It would mean no future migration as well. 

What do you think would be a good way to distinguish between them? A list of blessed keys (can be done entirely in platform), or a separate API (requires core changes)?

**Comment by gorhill** [comment]
I think platform code could expose a `vAPI.storage.cache` API, which would be used by uBO core for things which are impermanent data. How to implement this would be for the platform to decide. For example, for Chromium I am thinking of just adding a thin layer where `vAPI.storage.local` would prefix the keys with `settings/` while a `vAPI.storage.cache` would prefix with `cache/` and both would end up using `chrome.storage.local`.

**Comment by nikrolls** [comment]
Perfect! I'll update this PR with that implementation and leave it here until the core is updated. Thanks 😃

**Comment by gorhill** [comment]
I just added `vAPI.cacheStorage`, which is to be used to store transient data.

**Comment by nikrolls** [comment]
Perfect! I've updated this code with a first (untested) cut. I'll pull the latest core code and give it a go.

I also realised that this setup will also make moving back to local storage easier once Edge supports unlimited. Simply because I don't need to do any migration for a cache.

**Comment by ansorg** [comment]
hi guys
not sure whether this applies to the usage in an Extension and it probably would affect only phones with limited storage ... there is also a size limit for indexedDb in Edge, see https://msdn.microsoft.com/en-us/library/mt732551(v=vs.85).aspx

**Comment by nikrolls** [comment]
Thanks, that's good to bear in mind. I think we'd easily be in the 250MB range for any computer or tablet, but if Edge extensions ever come to phone we can revisit.

**Pull request merged**
