### PR TITLE
Remove storage workarounds now that Edge supports unlimited storage

### PR DESCRIPTION
**Pull request by nikrolls**
Leaving this here for later merging ...

Edge in Insider builds now supports unlimited browser storage, so we can do away with this superfluous code and reap the performance benefits.

https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/extension-api-roadmap/

### CODE REVIEW

**Comment by japborst** [comment]
I also see that storage.sync is in the works. Awesome stuff :)

**Comment by peteygao** [comment]
Sorry for being a party pooper, but what about users of Edge that don't have the latest version(s) of Edge (for one reason or another, they can't upgrade their OS--since Edge is tied to the OS and can't be updated independently, even though many considers it to be an "evergreen browser"...)?

Would it be possible to have feature detection and fallback to this code path if the version of Edge browser is `< someVer`? If feature detection is not possible because Edge doesn't expose storage limits via any official API, then explicit version detection, perhaps?

**Comment by japborst** [comment]
It's there for later merging, so it'll still work on non-insider previews. Or are you referring that you may not be able to upgrade from the Anniversary Update to Creators Update? 

I suppose version checking could work, so it can even be merged before the Creators Update is released :)

**Comment by nikrolls** [comment]
Yeah, I haven't looked into that yet. I know for sure it will be in CU, and the Edge team is looking into whether they can back-port it to AU in a cumulative update. The Store can tell me the percentage of people using which version and I can make a decision based on that.

I may be able to version detect, but if not I could feature detect by trying to save something bigger than 1MB into storage on startup and switching to IndexedDB if that fails. I could also specify a minimum version in Store, but that would mean I'd have to maintain a legacy branch and I don't want to do that.

This PR represents the ideal outcome where we can remove the old code  entirely, but it will be updated with whatever solution we  ultimately go with.

**Comment by peteygao** [comment]
Yes indeed, I do mean not being able to updated from Anniversary Update to Creator's Update.

I'm using a Lenovo T430 and there are severe software incompatibilities even with updating to the Anniversary Update that I will not be attempting an update to Creator's Update, and I'm sure there are other uBlock Edge users that are in the same boat.

Good to know that this issue is being taken into account :)

**Comment by nikrolls** [comment]
@japborst #68

**Comment by nikrolls** [comment]
I've changed this so it will still use IndexedDB on pre-Creators Update versions of Edge.

**Pull request merged**
