### PR TITLE
Workaround to allow URLs with hashes to be reloaded

### LINKED ISSUE #47: Refresh button in uBlock panel doesn't refresh a page that has an url containing a '#'
#### To reproduce: 
1. Go to a url with a hash-part, eg: https://en.wikipedia.org/wiki/UBlock_Origin#History
2. Open the uBlock panel and make a change; eg: one of the advanced filters or deactivating uBlock itself.
3. Click the refresh button that has appeared
   ublockrefresh
4. While the button reacts and disappears, the page doesn't refresh to apply the changes. 

#### Additional info:
* While the page doesn't refresh, it acts as if you'd gone to the address bar and pressed 'enter', ie: if you first scroll up to the top of the page, it'll scroll back down to the "History" section. 
* On urls without hashes, it works fine.
* Works fine on the Chrome version.

### Settings

- Browser/version: Edge 38.14393.0.0
- uBlock Origin version: 1.10.2
- Default settings, no filter lists, no custom filters.

### PR DESCRIPTION
**Pull request by nikrolls**
Fixes #47

### CODE REVIEW

**Comment by japborst** [comment]
That was quick. Nice implementation btw. All far from ideal, but it works. You know if tabs.reload is worked on? It isn't on the roadmap.

**Comment by nikrolls** [comment]
Not 100% sure. It's hard to tell based on the latest comment on https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9107382/. I will ask the Edge team in the new year.

**Comment by stkb** [comment]
I was going to try this method but you beat me to it :) Does this not add about:blank to the navigation history?

**Comment by japborst** [comment]
AFAIK about:blank is never added to the history.

**Comment by stkb** [comment]
@japborst Good point.

@nikrolls Just tried it out and it works well 👍 It does add an extra history entry for the url itself each time, but I guess it's not a big problem. Thanks!

**Comment by nikrolls** [comment]
Hmm, that's a shame. Let me play with it a little more, I may be able to execute some JavaScript in the page or something instead.

**Comment by nikrolls** [comment]
Ok, this solution seems to work, even on pages where CSP doesn't allow inline or evaluated scripts.

**Comment by stkb** [comment]
Works fine for me! Though I've now noticed another small issue.

This is maybe being super picky, but the scroll position of the page isn't saved when reloading; it goes back to the top. In Chrome it is.

From investigation, it seems that unlike in Chrome and Firefox, `location.reload()` in Edge doesn't save the scroll position. (Unlike pressing F5 or the toolbar button, which does.) However  I can't find any mention of this in the Edge platform issues, nor anywhere else on the internet for that matter. Though I don't have access to an insider build right now, and maybe it's already fixed in a newer Edge version.

**Comment by japborst** [comment]
Can't test this right now, but I figure that the following will work;
```
vAPI.tabs.injectScript(tabId, { code: 'var y = window.scrollY; window.location.reload(); window.scrollTo(0, y)' });
```

**Comment by stkb** [comment]
I think that's on the right track, but doesn't it work because the 3rd statement, `window.scrollTo(0, y)` gets called before the page reloads. I've tried putting it in an `onload` handler within the code but with no success: I think the handler gets wiped on reload.

It may be possible to solve it by posting the scroll position back to the extension first through messaging.

**Comment by japborst** [comment]
Ah yes of course. To confirm, this still exists in the latest slow ring build (14986).

**Comment by nikrolls** [comment]
This appears to be related to the browser rather than the workaround. Chrome attempts to maintain scroll position during a programmatic reload; Edge doesn't. I'm going to merge this so we can get the fix into the next release.

**Pull request merged**
