### PR TITLE
Disable cloud support

### PR DESCRIPTION
**Pull request by japborst**
As Edge is not going to enable cloud syncing in the near future, this PR disables the ability to enable cloud support and inform the user.

Method is implemented in the general files and should work for all other browsers as well as it relies on the platform-dependent `vapi-background.js` that needs to explicitly set `isSupported` to `false`.

Any feedback is welcome.

### CODE REVIEW

**Comment by japborst** [comment]
Personally, I'd prefer checking if `vAPI.cloud.push` and vAPI.cloud.pull` is a function. Currently for Edge, though, both are a function albeit empty (noop) to avoid all kinds of errors. This could potentially be avoided through checking if both are a function in the [listen callback cases](https://github.com/japborst/uBlock-Edge/blob/feature-disabledcloud/src/js/messaging.js#L662).

**Comment by nikrolls** [comment]
Yeah, I made those noops temporarily just to get it working. You can actually check for the existence of `browser.storage.sync` to tell if the browser supports settings synchronization (it's `undefined` in Edge).

I agree with this in principle, but considering it requires changes to the global source I think it would be good to see if we could get this functionality into the core repo first. We can then use it in this fork. We could fall back to diverging from the global source only if we're unable to get it to the core repo.

**Comment by japborst** [comment]
@nikrolls `browser.storage.sync` only works in Chromium, I'm afraid. Firefox uses a different API. That's one of the reasons why `vAPI.cloud` is implemented platform-dependent.

So we can do 2 things here:
 1. Propose this PR in the core repo
 1. Disable the cloud option somewhere in `/platform/edge/`

The only issue I have with number 2 (and why I implemented it in this way), is that the dashboard and options are handled globally. Changing it just for Edge would lead to a somewhat hacky result...

I'll propose this to the core repo and see what their thoughts are.

Thanks

**Comment by nikrolls** [comment]
Yeah, what I meant was to still use the `vAPI.cloud.isSupported` flag, but then implement it in each platform's `vapi-background.js` file. In Edge you could just have false for now, but we could eventually feature-detect once it's supported in Insider versions. That way it's officially supported by the core extension and you also don't have to do the `undefined` check.

**Comment by gorhill** [comment]
I can change the platform-independent code so that an platform-dependent implementation does not have to implement `vAPI.cloud` at all. Would that work?

**Comment by japborst** [comment]
@gorhill I have thought about taking that approach as well. That'd possibly be even better and have the settings check if `vAPI.cloud` even exists.

**Comment by nikrolls** [comment]
@gorhill Yep, that sounds even better. Thanks very much!

**Comment by japborst** [comment]
@nikrolls cloud support is now optional as of https://github.com/gorhill/uBlock/commit/2e953b45c9693552289f3bad134ea09a2f5e1bee. So if you merge everything back in here, I can change this PR to adapt to that situation.

**Comment by gorhill** [comment]
>  I can change this PR to adapt to that situation.

Why change anything? This pull request should just be closed. The only thing left to do is to remove entirely `vAPI.cloud` from the platform code.

Also, regarding a comment regarding indentation in another pull request:

> This was actually intended, makes more sense IMHO

You should always, always respect the style of the project you are contributing to regardless of whether you agree with it, and surely never bring in pointless changes like this. This is exactly one of the many reasons I refuse pull requests myself.

**Comment by japborst** [comment]
> Why change anything?
Instead of asking @nikrolls to have `vAPI.cloud` removed, it is a small effort to change this PR to do just that. But if that's not desired, me or @nikrolls can just close this.

> You should always, always respect the style of the project you are contributing to regardless of whether you agree with it
Fair point. That's the reason I reverted the indentation to the original state before it was merged yesterday.

**Comment by nikrolls** [comment]
It was easy enough to just remove the cloud object in `1.9.15rc0-edge`, so I've done that. I'll close this PR, but thanks @japborst for kicking this off and @gorhill for the upstream work!

**Comment by japborst** [comment]
@nikrolls awesome, thanks :)

**Comment by gorhill** [comment]
> It was easy enough to just remove the cloud object

Forgot to mention you do not need anymore to remove `vAPI.cloudStorage`, since you mentioned above that testing for the existence `browser.storage.sync` works, I added code to do just this in Chromium platform -- which is also useful for Firefox's webext version.

**Pull request closed without merging**
